---
sidebar: sidebar 
permalink: get-started/cache-intro.html 
keywords: how bluexp volume caching works, what is volume caching, bluexp 
summary: 卷缓存可在远程位置提供永久性可写卷。您可以使用BlueXP卷缓存加快数据访问速度、或者从访问量较多的卷卸载流量。缓存卷非常适合读取密集型工作负载、尤其是客户端需要重复访问相同数据的情况。 
---
= 了解BlueXP卷缓存
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
卷缓存是ONTAP 9软件的一项功能、它是一项远程缓存功能、可简化文件分发、通过使资源更靠近用户和计算资源所在位置来减少WAN延迟、并降低WAN带宽成本。卷缓存可在远程位置提供永久性可写卷。您可以使用BlueXP卷缓存加快数据访问速度、或者从访问量较多的卷卸载流量。缓存卷非常适合读取密集型工作负载、尤其是客户端需要重复访问相同数据的情况。

借助BlueXP卷缓存、您可以缓存云、尤其是Amazon FSx for NetApp ONTAP、Cloud Volumes ONTAP以及作为工作环境的内部环境。

该服务还允许分支机构访问公司数据集。通过提供需要从集群中的多个控制器频繁访问的数据_HOT data_、您可以提高交付给关键应用程序的性能。此外、通过为全球多个位置的用户缓存本地热数据、您可以同时访问集中式数据集、同时缩短访问热数据时他们收到的响应时间、从而增强他们的协作。



== 什么是缓存？

缓存是驻留在主机和数据源之间的临时存储位置。缓存的目标是、以一种比从源中提取数据更快的速度提供数据的方式存储经常访问的部分源数据。在读取密集型环境中、缓存的优势最大、在这种环境中、数据会被多次访问并由多个主机共享。缓存系统比具有数据源的系统速度更快、这是通过更快的存储系统以及靠近主机的缓存存储空间实现的。



== 使用BlueXP卷缓存的优势

BlueXP卷缓存具有以下优势：

* 提高混合云基础架构的性能
* 通过将数据从一个云提供商缓存到另一个云提供商来消除云孤岛
* 降低存储成本
* 跨地理位置协作
* 在BlueXP中使用NetApp托管的服务
* 能够更快地适应不断变化的IT环境
* 云中托管的按需或基于订阅的卷缓存




== BlueXP卷缓存功能的用途

通过BlueXP卷缓存、您可以充分利用多种NetApp技术来实现以下目标：

通过BlueXP卷缓存服务、您可以充分利用多种NetApp技术来实现以下目标：

* 将数据从一个云提供商缓存到另一个云提供商
* 查看和编辑缓存导出策略
* 调整现有缓存的大小
* 删除缓存




== 成本

NetApp不会因使用BlueXP卷缓存服务而向您收费、但您需要检查云提供商是否收取适用的数据传入和传出费用。



== 许可

BlueXP卷缓存不需要特殊的ONTAP许可证。



== BlueXP卷缓存的工作原理

缓存卷是一种稀疏填充的卷、由源卷提供支持。缓存卷可以与源卷位于同一集群上、也可以与源卷位于不同集群上。

通过缓存卷、可以访问源卷中的数据、而无需将所有数据都放在缓存卷中。通过仅保留热数据(工作数据或最近使用的数据)、可以高效管理缓存卷中的数据存储。

如果缓存卷包含客户端请求的数据、则BlueXP卷缓存将读取请求。否则、卷缓存服务会先从源卷请求数据并存储数据、然后再处理客户端请求。然后、系统将直接从缓存卷处理后续的数据请求。这样可以提高重复访问相同数据时的性能、因为在第一次请求后、数据不再需要通过网络传输或从过载的系统提供。
